import Foundation

struct LocationData {
    static let stops: [String] = [
        "Adana Otogarı",
        "Adıyaman Otogarı",
        "Afyonkarahisar Otogarı",
        "Ağrı Otogarı",
        "Aksaray Otogarı",
        "Amasya Otogarı",
        "Ankara AŞTİ",
        "Antalya Otogarı",
        "Alanya Otogarı",
        "Ardahan Otogarı",
        "Artvin Otogarı",
        "Aydın Otogarı",
        "Balıkesir Otogarı",
        "Bartın Otogarı",
        "Batman Otogarı",
        "Bayburt Otogarı",
        "Bilecik Otogarı",
        "Bingöl Otogarı",
        "Bitlis Otogarı",
        "Bolu Otogarı",
        "Burdur Otogarı",
        "Bursa Otogarı",
        "Çanakkale Otogarı",
        "Çankırı Otogarı",
        "Çorum Otogarı",
        "Denizli Otogarı",
        "Diyarbakır Otogarı",
        "Düzce Otogarı",
        "Edirne Otogarı",
        "Elazığ Otogarı",
        "Erzincan Otogarı",
        "Erzurum Otogarı",
        "Eskişehir Otogarı",
        "Gaziantep Otogarı",
        "Giresun Otogarı",
        "Gümüşhane Otogarı",
        "Hakkari Otogarı",
        "Hatay Otogarı",
        "Iğdır Otogarı",
        "Isparta Otogarı",
        "İstanbul Esenler Otogarı",
        "İstanbul Alibeyköy Otogarı",
        "İstanbul Harem Otogarı",
        "İstanbul Dudullu Otogarı",
        "İzmir Otogarı",
        "Kahramanmaraş Otogarı",
        "Karabük Otogarı",
        "Karaman Otogarı",
        "Kars Otogarı",
        "Kastamonu Otogarı",
        "Kayseri Otogarı",
        "Kırıkkale Otogarı",
        "Kırklareli Otogarı",
        "Kırşehir Otogarı",
        "Kilis Otogarı",
        "Kocaeli (İzmit) Otogarı",
        "Gebze Otogarı",
        "Konya Otogarı",
        "Kütahya Otogarı",
        "Malatya Otogarı",
        "Manisa Otogarı",
        "Mardin Otogarı",
        "Mersin Otogarı",
        "Muğla Otogarı",
        "Bodrum Otogarı",
        "Fethiye Otogarı",
        "Marmaris Otogarı",
        "Muş Otogarı",
        "Nevşehir Otogarı",
        "Niğde Otogarı",
        "Ordu Otogarı",
        "Osmaniye Otogarı",
        "Rize Otogarı",
        "Sakarya (Adapazarı) Otogarı",
        "Samsun Otogarı",
        "Siirt Otogarı",
        "Sinop Otogarı",
        "Sivas Otogarı",
        "Şanlıurfa Otogarı",
        "Şırnak Otogarı",
        "Tekirdağ Otogarı",
        "Tokat Otogarı",
        "Trabzon Otogarı",
        "Tunceli Otogarı",
        "Uşak Otogarı",
        "Van Otogarı",
        "Yalova Otogarı",
        "Yozgat Otogarı",
        "Zonguldak Otogarı"
    ]
}
